### ISSUE TITLE
Auto Restart and Application?

### ISSUE THREAD

**Issue by Dontmindmes** [capnspacehook/taskmaster#1]
Hey say i have an application in  a folder called C:\AppData

how can i have calc.exe rerun every say 5 minutes?

**Comment by capnspacehook** [comment]
Hi @Dontmindmes, thanks for checking out Taskmaster!

This is a perfect use of the RepetitionPattern Trigger options: https://godoc.org/github.com/capnspacehook/taskmaster#RepetitionPattern

Great docs from MS on it: https://docs.microsoft.com/en-us/windows/desktop/api/taskschd/nn-taskschd-irepetitionpattern

I just pushed an example that creates a scheduled task that restarts calc every 5 minutes, that example and the docs should give you enough information to do what you want.

Repeating task example: https://github.com/capnspacehook/taskmaster/blob/master/examples/createRepeatingTask/repeatingTask.go

**Comment by Dontmindmes** [comment]
I just saw it right now, does the one you just pushed right now restart calc every 5 minutes as long as its running? or even after its done running? because im looking for something to keep it launching it every 5 minutes even after its done runnign

**Comment by capnspacehook** [comment]
The example I pushed creates a TimeTrigger with the `StopAtDurationEnd` attribute set to true, so the program launched by the created task is killed if it is still running and restarted. Does that answer your question?

**Comment by Dontmindmes** [comment]
Yes thanks
amazing project btw, 2 more questions xD

1. How do i have it execute a spesific file? "C:\ProgramData\NamedExtention\file.exe"
i couldnt figure it out

and how do i disable it? I ran it on my pc and i dont want it constantly running xD it keeps opening calc xD reee

**Comment by Dontmindmes** [comment]
newTaskDef.AddExecAction("C:\\ProgramData\\NameFolderExtesion\\calc.exe", "", "", "Pop Calc")

would this work? also i cant seem to find where to remove the task

**Comment by capnspacehook** [comment]
1. Just replace `calc.exe` with the path to an executable in `AddExecAction`. I would highly recommend reading the GoDoc, for this and all Go repos you plan an using, as such questions are often answered in the documentation.
2. The easiest way would be to open up the Task Scheduler program on your computer disabling it in there. You could do it with taskmaster as well, or Powershell cmdlets, but through the GUI is easiest.

**Comment by Dontmindmes** [comment]
I cant do it through gui since it says can not open msc

i tried doing it through powershell but i get an error
Disable-ScheduledTask -taskname "New Task"

https://gyazo.com/dff6e3c2ab9077dc36bed3cddb32739b
