### ISSUE TITLE
AddMonthlyTrigger/AddMonthlyTriggerEx signatures don't allow for more than one day a month

### ISSUE THREAD

**Issue by creativeprojects** [capnspacehook/taskmaster#10]
Hi,

There's something funny about the AddMonthlyTrigger signatures is that it doesn't allow to give more than one day a month. I would have expected the method signature to follow that of AddWeeklyTrigger or AddMonthlyDOWTrigger in which you can provide a selection of days of the week and months of the year.

```go
func (d *Definition) AddMonthlyTrigger(dayOfMonth int, monthOfYear Month, randomDelay period.Period, startBoundary time.Time)
func (d *Definition) AddMonthlyTriggerEx(dayOfMonth int, monthOfYear Month, randomDelay period.Period, id string, startBoundary, endBoundary time.Time, timeLimit, repetitionDuration, repetitionInterval period.Period, stopAtDurationEnd, enabled bool) error
```

Instead it would make more sense to have

```go
func (d *Definition) AddMonthlyTrigger(dayOfMonth DayOfMonth, monthOfYear Month, randomDelay period.Period, startBoundary time.Time)
func (d *Definition) AddMonthlyTriggerEx(dayOfMonth DayOfMonth, monthOfYear Month, randomDelay period.Period, id string, startBoundary, endBoundary time.Time, timeLimit, repetitionDuration, repetitionInterval period.Period, stopAtDurationEnd, enabled bool) error
```

You might not be able to change the signature for compatibility with others already using these methods, so I guess it's probably better to make new ones? what do you think?

**Comment by capnspacehook** [comment]
Good catch, that was an error not making the first parameter a `DayOfMonth` type. I simplified the `Definition` API and removed those kinds of functions entirely, so the issue should be resolved.
