### ISSUE TITLE
Stop task?

### ISSUE THREAD

**Issue by Dontmindmes** [capnspacehook/taskmaster#2]
how would i programmatically stop task?

https://github.com/capnspacehook/taskmaster/tree/master/examples/runRegisteredTask

**Comment by capnspacehook** [comment]
Please read taskmaster's associated Godoc. RunningTask objects have a Spot method which can be used.

**Comment by Dontmindmes** [comment]
I tried doing it but wasn't able to

I also tried deleting the task using Windows cmd command and wasn't able to do it using exec.command
