### ISSUE TITLE
Task with no TimeLimit is always stopped after 3 days running

### ISSUE THREAD

**Issue by baptistedonaux** [capnspacehook/taskmaster#7]
When I create a task from a definition with no `TimeLimit` (into `Settings`) or with an empty period, the task created will be stopped after 3 days.

# Use cases
## Definition 1
`TimeLimit` is sets with no period.

```go
def := taskmaster.Definition{
        // others parameters…

	Settings: taskmaster.TaskSettings{
                // no TimeLimit sets
	},
}
```

## Definition 2
`TimeLimit` is sets with empty period.

```go
def := taskmaster.Definition{
        // others parameters…

	Settings: taskmaster.TaskSettings{
		TimeLimit: period.Period{},
	},
}
```

## Result
Task created contains always a `TimeLimit` equal to `P72H`.

![Capture](https://user-images.githubusercontent.com/3277332/87947587-d7f72600-caa3-11ea-84cc-1704c373fd2b.PNG)
PS: French edition - Can be translated by "Stop the task if it runs more than 3 days"

# Problem
I have make some research and I think the problem comes from function [`PeriodToString`](https://github.com/capnspacehook/taskmaster/blob/84d1d8b1d84d67da662a658f58a03668d1ac6a76/utils.go#L66) (from **utils.go**) which convert empty period to empty string instead of `P0D`.

I don’t know why this condition has been written but about `TimeLimit`, to set no **execution time limit**, the value to send must be `P0D`.

**Comment by baptistedonaux** [comment]
I propose you a basic fix but a better solution should be developed.

**Comment by capnspacehook** [comment]
Sorry about the delay in fixing this, I've been pretty busy lately. There are a few properties that require a non-zero period value, but the timelimit property of Settings isn't one of them. I guess I never bothered to figure out what properties could take "P0D" and what properties could, so I just used the helper func `PeriodToString` when writing to all of them to be safe.
