### ISSUE TITLE
Little help with pre-validation on some fields to avoid a panic

### ISSUE THREAD

**Issue by creativeprojects** [capnspacehook/taskmaster#9]
Hi,

First of all, thanks for this handy library :+1: 

Just a note if you want to add some pre-validation on some fields:
I was doing something stupid in a MonthlyTrigger using `2^month` for calculating _month of the year_ instead of `2^(month-1)` and didn't notice straight away. But sometimes I was getting a panic:

```
   error:      Exception occurred.
   stack:      goroutine 1 [running]:
github.com/go-ole/go-ole/oleutil.MustPutProperty(0x1d8cde0, 0xb1d4b1, 0xc, 0xc0003b79e0, 0x1, 0x1, 0xc0003ad2a0)
   D:/go/pkg/mod/github.com/go-ole/go-ole@v1.2.4/oleutil/oleutil.go:86 +0xd7
github.com/capnspacehook/taskmaster.fillTaskTriggersObj(0xc000004480, 0x2, 0x2, 0x1d8be20, 0x0, 0x0)
   D:/go/pkg/mod/github.com/capnspacehook/taskmaster@v0.0.0-20190802050140-eebf732b5748/parse.go:762 +0x1670
github.com/capnspacehook/taskmaster.fillDefinitionObj(0xc0001b0eb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
   D:/go/pkg/mod/github.com/capnspacehook/taskmaster@v0.0.0-20190802050140-eebf732b5748/parse.go:581 +0x535
github.com/capnspacehook/taskmaster.(*TaskService).modifyTask(0xc000060f00, 0xc00039bf80, 0x20, 0xc0001b0eb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
   D:/go/pkg/mod/github.com/capnspacehook/taskmaster@v0.0.0-20190802050140-eebf732b5748/manage.go:500 +0x183
github.com/capnspacehook/taskmaster.(*TaskService).CreateTaskEx(0xc000060f00, 0xc00039bf80, 0x20, 0xc0001b0eb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
   D:/go/pkg/mod/github.com/capnspacehook/taskmaster@v0.0.0-20190802050140-eebf732b5748/manage.go:437 +0x519
github.com/capnspacehook/taskmaster.(*TaskService).CreateTask(0xc000060f00, 0xc00039bf80, 0x20, 0xc0001b0eb0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
   D:/go/pkg/mod/github.com/capnspacehook/taskmaster@v0.0.0-20190802050140-eebf732b5748/manage.go:393 +0xc3
[...]
```

and the panic was triggered at that line in _parse.go_:

```go
	oleutil.MustPutProperty(monthlyTriggerObj, "MonthsOfYear", int(monthlyTrigger.MonthsOfYear))
```

It was giving me a similar panic on DaysOfWeek and DaysOfMonth.

I think a little pre-validation could help distracted developers like me :disappointed: up to you

**Comment by capnspacehook** [comment]
It definitely could, thanks for bringing this to my attention. I'm working on a fix now 👍🏼

**Comment by capnspacehook** [comment]
Added some validation here: ddc5d9fd9a572bae8ecc98714765895208ad0066. Let me know if this solves the issue. There is more validation I can do, and I'll add more as I figure out exactly what Task Scheduler wants. It's so complicated lol

**Comment by creativeprojects** [comment]
Yes 👍 I think it looks pretty good, thanks 😃

**Comment by capnspacehook** [comment]
If you run into anything else you think could be pre-validated, don't hesitate to let me know! Thanks for using taskmaster!
